### ISSUE TITLE
After off switch, break octoprint, and must restart raspberry pi

### ISSUE THREAD

**Issue by Smolinec** [Salamafet/ophom#43]
2021-06-06 17:13:56,360 - octoprint.server.util.flask - DEBUG - Using translation core folder /home/pi/.octoprint/translations for locale cs
2021-06-06 17:13:57,274 - octoprint.plugins.autologin_config - INFO - Autologin settings saved
2021-06-06 17:14:08,550 - octoprint.server.api - ERROR - Error calling SimpleApiPlugin ophom
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/api/__init__.py", line 94, in pluginData
    response = api_plugin.on_api_get(request)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1941, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_phom/__init__.py", line 235, in on_api_get
    id_lamp = re.search(r"\/lights\/(\d)\/state", action['address']).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2021-06-06 17:14:48,904 - octoprint.server.util.sockjs - INFO - New connection from client: ::ffff:192.168.88.254
2021-06-06 17:14:48,979 - octoprint.events.fire - DEBUG - Firing event: ClientOpened (Payload: {'remoteAddress': '::ffff:192.168.88.254'})
2021-06-06 17:14:48,979 - octoprint.events - DEBUG - Sending action to <bound method PrinterStateConnection._onEvent of <octoprint.server.util.sockjs.PrinterStateConnection object at 0xa7a5c7f0>>
2021-06-06 17:14:48,980 - octoprint.plugin - DEBUG - Calling on_event on action_command_notification
2021-06-06 17:14:48,980 - octoprint.plugin - DEBUG - Calling on_event on action_command_prompt
2021-06-06 17:14:48,980 - octoprint.plugin - DEBUG - Calling on_event on announcements
2021-06-06 17:14:48,980 - octoprint.plugin - DEBUG - Calling on_event on file_check
2021-06-06 17:14:48,981 - octoprint.plugin - DEBUG - Calling on_event on firmware_check
2021-06-06 17:14:48,981 - octoprint.plugin - DEBUG - Calling on_event on pluginmanager
2021-06-06 17:14:48,981 - octoprint.plugin - DEBUG - Calling on_event on softwareupdate
2021-06-06 17:14:48,981 - octoprint.plugin - DEBUG - Calling on_event on tracking
2021-06-06 17:14:48,981 - octoprint.plugin - DEBUG - Calling on_event on DisplayLayerProgress
2021-06-06 17:14:48,988 - octoprint.server.util.sockjs - INFO - New connection from client: ::ffff:192.168.88.254
2021-06-06 17:14:49,003 - octoprint.server.util.flask - INFO - Passively logging in user admin from ::ffff:192.168.88.254
2021-06-06 17:14:49,004 - octoprint.access.users - INFO - Logged in user: admin
2021-06-06 17:14:49,021 - octoprint.server.util.flask - INFO - Passively logging in user admin from ::ffff:192.168.88.254
2021-06-06 17:14:49,021 - octoprint.access.users - INFO - Logged in user: admin
2021-06-06 17:14:49,051 - octoprint.server.util.sockjs - DEBUG - Socket message held back until permissions cleared, added to backlog: plugin
2021-06-06 17:14:49,051 - octoprint.server.util.sockjs - DEBUG - Socket message held back until permissions cleared, added to backlog: plugin
2021-06-06 17:14:49,108 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin announcements
2021-06-06 17:14:49,108 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin logging
2021-06-06 17:14:49,108 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin appkeys
2021-06-06 17:14:49,109 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin discovery
2021-06-06 17:14:49,110 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin errortracking
2021-06-06 17:14:49,111 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin action_command_prompt
2021-06-06 17:14:49,112 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin gcodeviewer
2021-06-06 17:14:49,113 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin action_command_notification
2021-06-06 17:14:49,114 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin pluginmanager
2021-06-06 17:14:49,114 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin corewizard
2021-06-06 17:14:49,115 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin softwareupdate
2021-06-06 17:14:49,116 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin tracking
2021-06-06 17:14:49,116 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin backup
2021-06-06 17:14:49,117 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin prusaslicerthumbnails
2021-06-06 17:14:49,118 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin ophom
2021-06-06 17:14:49,118 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin youtube_timelapse
2021-06-06 17:14:49,119 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin telegram
2021-06-06 17:14:49,120 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin resource_monitor
2021-06-06 17:14:49,120 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin prusa_mini_eta
2021-06-06 17:14:49,121 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin pi_support
2021-06-06 17:14:49,122 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin MultipleUpload
2021-06-06 17:14:49,123 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin fullscreen
2021-06-06 17:14:49,123 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin firmwareupdater
2021-06-06 17:14:49,125 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin firmware_check
2021-06-06 17:14:49,126 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin file_check
2021-06-06 17:14:49,126 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin dashboard
2021-06-06 17:14:49,126 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin autologin_config
2021-06-06 17:14:49,126 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin octolapse
2021-06-06 17:14:49,126 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin octoeverywhere
2021-06-06 17:14:49,127 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin googledrivebackup
2021-06-06 17:14:49,130 - octoprint.server.util.flask - DEBUG - Using translation plugin folder /home/pi/oprint/lib/python3.7/site-packages/octoprint_DisplayLayerProgress/translations from plugin DisplayLayerProgress for locale cs
2021-06-06 17:14:49,130 - octoprint.server.util.flask - DEBUG - No translations for locale cs from plugin bedlevelvisualizer

**Comment by Salamafet** [comment]
Hi,

Sorry for not getting back to you sooner.
I can't see any error help me to help you in this log.

Is ophom correctly configured ?
